version: '2'

services:

  ########################################################
  # Home Assistant
  ########################################################
  home-assistant:
    image: homeassistant/home-assistant:0.61.1
    environment:
      - "TZ=Europe/Berlin"
      - "COFFEE_FLASH_BASE_URL=http://flash-home.duckdns.org:3000/"
      - "PROVIDER_FLASH_BASE_URL=http://flash-home.duckdns.org:3001/"
    ports:
      - 80:8123  # Home Assistant
      - 1883:1883  # MQTT
    volumes:
      - ./home-assistant/config:/config

  ########################################################
  # Coffee Machine Client
  ########################################################
  coffee-client:
    build: coffee-client
    environment:
      - "FLASH_COFFEE_URL=http://flash-coffee:3000"
      - "FLASH_COFFEE_USERNAME=user_one"
      - "FLASH_COFFEE_PASSWORD=password_one"
      - "FLASH_PROVIDER_URL=http://flash-provider:3000"
      - "FLASH_PROVIDER_USERNAME=user_two"
      - "FLASH_PROVIDER_PASSWORD=password_two"
      - "MQTT_HOST=home-assistant"
      - "MQTT_PORT=1883"
      - "INIT_SLEEP=5"
    depends_on:
      - flash-coffee
      - flash-provider
      - home-assistant

  ########################################################
  # Flash Server Coffee Machine
  ########################################################
  flash-coffee:
    build: flash-server
    environment:
      - "IOTA_SEED=ECRUQZGHBGSIGINQV9FK9EWZZTODYCKTGLITLHUNFKIOAFQYWSUIXQDSKZYHOVLBIXWKRIXDNARDYADKU"
      - "IRI_HOST=http://iota-node.duckdns.org"
      - "IRI_PORT=14267"
      - "IRI_TESTNET=true"
      - "AUTH_USERNAME=user_one"
      - "AUTH_PASSWORD=password_one"
      - "MONGODB_URL=mongo-coffee"
    ports:
      - "3000:3000"
    depends_on:
      - mongo-coffee

  mongo-coffee:
    image: mongo
    ports:
      - "27017:27017"

  ########################################################
  # Flash Server Service Provider
  ########################################################
  flash-provider:
    build: flash-server
    environment:
      - "IOTA_SEED=UXSVWCUKNZKOVYTWPWEF9KBHZLNSDGYDVBJGNYJKF9MZIOTSFCHRYNCKUQIYXBCILTVXL9NFMFIKQLUGX"
      - "IRI_HOST=http://iota-node.duckdns.org"
      - "IRI_PORT=14267"
      - "IRI_TESTNET=true"
      - "AUTH_USERNAME=user_two"
      - "AUTH_PASSWORD=password_two"
      - "MONGODB_URL=mongo-provider"
    ports:
      - "3001:3000"
    depends_on:
      - mongo-provider

  mongo-provider:
    image: mongo
    ports:
      - "27018:27017"
