version: '2'

services:
  home-assistant:
    image: homeassistant/home-assistant:0.61.1
    environment:
      - "TZ=Europe/Berlin"
    ports:
      - 8123:8123
      - 1883:1883
    volumes:
      - ./config:/config
