homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.2
  longitude: 16.3667
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  # Customization file
  customize: !include customize.yaml

http:

frontend:
  javascript_version: es5
  extra_html_url:
    - /local/custom_ui/state-card-value_only.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-value_only.html
    - /local/custom_ui/state-card-tiles_es5.html

# Sensor definitions
sensor:
  - platform: mqtt
    name: coffee machine state
    state_topic: "/coffee/state"
    value_template: '{{ value_json.state }}'
  - platform: mqtt
    name: coffee machine balance
    state_topic: "/coffee/flash"
    unit_of_measurement: MIOTA
    value_template: '{{ value_json.flash[0].flash.deposit[0] / 1000000 }}'
  - platform: mqtt
    name: coffee machine addresses
    state_topic: "/coffee/flash"
    value_template: '{{ value_json.flash[0].flash.multisigDigestPool | length}}'

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: iota
  password: flash
  embedded:
     listeners:
        default:
           max-connections: 50000
           bind: 0.0.0.0:1883
           type: tcp
     auth:
        plugins: ['auth.anonymous'] #List of plugins to activate for authentication among all registered plugins
        allow-anonymous: false
        password-file: /config/mqtt_passwd

weblink:
  entities:
    - name: coffee_machine_transaction
      url: http://iota-node.duckdns.org:8081/
    - name: coffee_provider_transaction
      url: http://iota-node.duckdns.org:8081/

# custom components
coffee_transaction_weblinks:
coffee_state_listener:
documentation:

#iota:
#  iri: https://testnet140.tangle.works:443
#  testnet: true
#  wallets:
#    - name: Default Wallet
#      seed: OYYAHJDBNPHLVCKWMVBCYBYSUSSWLIDQ9AAXOMAMAMSUA9Y9PWXOCYGXIMLLBURGRHEZAZPEMUIXVIVQC

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
