homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 48.2
  longitude: 16.3667
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vienna
  # Customization file
  customize: !include customize.yaml

# Enables configuration UI
#config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensor definitions
sensor:
  - platform: yr
  - platform: mqtt
    name: coffee machine state
    state_topic: "/coffee/state"
    value_template: '{{ value_json.state }}'
  - platform: mqtt
    name: coffee machine balance
    state_topic: "/coffee/state"
    unit_of_measurement: IOTA
    value_template: >-
          {% if value_json.flash %}
            {{ value_json.flash[0].flash.deposit[0] }}
          {% else %}
            0
          {% endif %}

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: iota
  password: flash
  embedded:
     listeners:
        default:
           max-connections: 50000
           bind: 0.0.0.0:1883
           type: tcp
     auth:
        plugins: ['auth.anonymous'] #List of plugins to activate for authentication among all registered plugins
        allow-anonymous: false
        password-file: /config/mqtt_passwd

#iota:
#  iri: https://testnet140.tangle.works:443
#  testnet: true
#  wallets:
#    - name: Default Wallet
#      seed: OYYAHJDBNPHLVCKWMVBCYBYSUSSWLIDQ9AAXOMAMAMSUA9Y9PWXOCYGXIMLLBURGRHEZAZPEMUIXVIVQC

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
