iri_config:
  name: IRI Node
  entities:
    - iota.iri
    - iota.is_testnet
    - sensor.iota_node

iota_wallet_1:
  name: Service Provider
  entities:
    - sensor.default_wallet_balance

iota_wallet_2:
  name: Customer
  entities:
    - sensor.zendi_wallet_balance

documentation:
  name: Documentation
  entities:
    - sensor.documentation

coffee_machine:
  name: Coffee Machine
  control: hidden
  entities:
    - script.coffee_single
    - script.coffee_double
    - sensor.coffee_machine_state
    - sensor.coffee_machine_balance
    - sensor.coffee_machine_addresses
    - script.coffee_init
    - script.coffee_fund
    -  script.coffee_close
    - sensor.coffee_machine_provider_transaction
    - sensor.coffee_machine_transaction
    - weblink.coffee_machine_transaction
    - weblink.coffee_provider_transaction